import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'KIN' | 'FR' | 'KIS' | 'ES';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    home: 'Home',
    live: 'Live',
    services: 'Services',
    bibleStudy: 'Bible Study',
    gallery: 'Gallery',
    branches: 'Branches',
    volunteer: 'Volunteer',
    serve: 'Serve',
    aboutUs: 'About Us',
    register: 'Register',
    give: 'Give',
    media: 'Media',
    videoSermons: 'Video Sermons',
    photoGallery: 'Photo Gallery',
    registrationTitle: 'Church Registration',
    registrationSub: 'Join our church family today',
    individual: 'Individual',
    family: 'Family',
    fullName: 'Full Name',
    familyName: 'Family Name',
    addMember: 'Add Member',
    familyMembers: 'Family Members',
    visitedBefore: 'Have you visited Grace Community before?',
    yesVisited: 'Yes, I have',
    noVisited: 'No, first time',
    completeRegistration: 'Complete Registration',
    dailyDevotional: 'Daily Devotional',
    startDayGrace: 'Start Your Day with Grace',
    devotionalSub: 'Click below to generate a unique, AI-powered devotional to inspire your walk with God today.',
    generateDevotional: 'Generate Today\'s Devotional',
    preparingInspiration: 'Preparing your inspiration...',
    reflection: 'Reflection',
    prayer: 'Prayer',
    generateAnother: 'Generate Another',
    volunteerTitle: 'Volunteer With Us',
    volunteerSubtitle: 'Ready to serve? Fill out the form below to join one of our ministry teams.',
    whyVolunteer: 'Why Volunteer?',
    makeDifference: 'Make a difference',
    makeDifferenceDesc: 'Make a difference in your church and community.',
    growSkills: 'Grow your skills',
    growSkillsDesc: 'Grow your skills and build lasting friendships.',
    serveGod: 'Serve God and others',
    serveGodDesc: 'Serve God and others with your unique gifts.',
    whoCanVolunteer: 'Who Can Volunteer?',
    anyoneCanVolunteer: 'Anyone with a willing heart to serve. All ages and backgrounds are welcome!',
    allAgesWelcome: 'All ages and backgrounds are welcome!',
    volunteerVerse: 'Each of you should use whatever gift you have received to serve others.',
    volunteerForm: 'Volunteering Form',
    volFullName: 'Full Name',
    volFullNamePlaceholder: 'Enter your full name',
    volEmail: 'Email Address',
    volEmailPlaceholder: 'Enter your email',
    volPhone: 'Phone Number',
    volPhonePlaceholder: 'Enter your phone number',
    volAddress: 'Home Address',
    volAddressPlaceholder: 'Enter your address',
    volMinistry: 'Where do you want to volunteer?',
    volSelectMinistry: 'Select a ministry',
    volAvailability: 'Your Availability',
    volSelectAvailability: 'Select your availability',
    volWhyQuestion: 'Why do you want to volunteer?',
    volWhyPlaceholder: 'Share your reason for wanting to volunteer...',
    submit: 'Submit',
    thankYou: 'Thank You!',
    volResponse: 'Our team will contact you to discuss your request and next steps.',
    bibleStudyGroups: 'Bible Study Groups',
    bibleStudySub: 'Deepen your understanding of Scripture and build lasting friendships in our small group Bible studies. We have groups for everyone.',
    viewAllGroups: 'View All Groups',
    scriptureLibrary: 'Scripture Verse Library',
    scriptureLibrarySub: 'Access our curated collection of direct Bible verses for every situation. Download and share these words of life.',
    exploreScriptures: 'Explore Scriptures',
    branchDetails: 'Branch Details',
    pastor: 'Pastor',
    serviceTimes: 'Service Times',
    aboutBranch: 'About this Branch',
    mission: 'Our Mission',
    history: 'Our History',
    worshippers: 'Worshippers',
    contactUs: 'Contact Us',
    scriptureLibraryTitle: 'Scripture Library',
    scriptureLibrarySubText: 'Explore direct words from the Bible categorized for your life\'s journey. Download a beautiful flyer of your favorite verse to keep or share.',
    printFlyer: 'Print Flyer',
    peaceComfort: 'Peace & Comfort',
    strengthCourage: 'Strength & Courage',
    hopeFuture: 'Hope & Future',
    ourServices: 'Our Services',
    servicesSub: 'We offer various ways to connect with God and our community throughout the week. Join us at any of our scheduled gatherings.',
    sundayWorship: 'Sunday Morning Worship',
    midWeekPrayer: 'Mid-Week Prayer',
    youthGathering: 'Youth Gathering',
    communityOutreach: 'Community Outreach',
    welcome: 'Welcome to Grace Community',
    heroTitle: 'Experience Grace, Find Community',
    heroSub: 'A place where faith meets fellowship. Join us as we grow together in Christ.',
    joinLive: 'Join Live',
    viewServices: 'View Services',
    liveNow: 'Live Now',
    onlineService: 'Join Our Online Service',
    watching: 'Watching',
    upcomingStreams: 'Upcoming Streams',
    ourBranches: 'Our Branches',
    findBranch: 'Find a Grace Community branch near you and join our family.',
    churchGallery: 'Church Gallery',
    capturingMoments: 'Capturing moments of faith, fellowship, and service.',
    heritage: 'Our Heritage',
    foursquareTitle: 'Foursquare Gospel Church',
    getInvolved: 'Ways to Get Involved',
    wantToBeChristian: 'Do you want to be a member of the Christian faith?',
    previousChurch: 'Which church are you coming from?',
    yesMember: 'Yes, I want to join',
    noMember: 'Not yet',
    voiceTranslation: 'Voice Translation',
    enableTranslation: 'Enable Live Translation',
    translating: 'Translating...',
    translationNotice: 'AI-powered real-time translation for our global family.',
    watchOnYoutube: 'Watch on YouTube',
    mediaExplorer: 'Media Explorer',
    recentSermons: 'Recent Sermons',
    photoHighlights: 'Photo Highlights',
    watchNow: 'Watch Now',
    viewGallery: 'View Gallery',
    ourMinistries: 'Our Ministries',
    ministriesSub: 'Discover the various ways we serve our community and grow together in Christ through our dedicated ministry teams.',
    childrensMinistry: "Children's Ministry",
    youthMinistry: 'Youth Ministry',
    evangelismMinistry: 'Evangelism Ministry',
    eduLeadershipMinistry: 'Christian Education & Leadership',
    mercyMinistry: 'Mercy Ministry',
    counselingMinistry: 'Counseling Ministry',
    learnMoreJoin: 'Learn More & Join',
    ministryImpact: 'Ministry Impact at a Glance',
    ministryName: 'Ministry Name',
    focusArea: 'Focus Area',
    meetingFreq: 'Meeting Frequency',
    status: 'Status',
    active: 'Active',
    sermonsResources: 'Sermons & Resources',
    sermonsSub: 'Nourish your soul with our latest teachings and study materials.',
    latestSermons: 'Latest Sermons',
    watch: 'Watch',
    listen: 'Listen',
    studyResources: 'Study Resources',
    download: 'Download',
    viewAllSermons: 'View All Sermons',
    viewAllResources: 'View All Resources',
    deeperWord: 'Deeper into the Word',
    inductiveStudy: 'Inductive Study',
    topicalStudy: 'Topical Study',
    characterStudy: 'Character Study',
    devotionalStudy: 'Devotional Study',
    viewStudyDetails: 'View Study Details',
    joinThisGroup: 'Join This Group',
    downloadStudyGuide: 'Download Study Guide',
    theLivingWord: 'The Living Word',
    livingWordSub: '"In the beginning was the Word, and the Word was with God, and the Word was God."',
    ourPhilosophy: 'Our Philosophy',
    illuminatingTruth: 'Illuminating the Truth',
    biblicalExcellence: 'Biblical Excellence',
    biblicalExcellenceSub: "We believe in the meticulous study of the scriptures, seeking the original intent and the timeless application of God's message.",
    communityScholars: 'Community of Scholars',
    communityScholarsSub: "Word Light is not just a church; it's a community of believers who are also students of the Word, growing together in wisdom and grace.",
    aiScriptureInsight: 'AI Scripture Insight',
    aiScriptureInsightSub: "Ask the AI for a deep theological insight on today's study...",
    foursquareDesc: 'Grace Community is a proud member of the International Church of the Foursquare Gospel. The term "Foursquare" represents the four-fold ministry of Jesus Christ as the Savior, Baptizer with the Holy Spirit, Healer, and Soon-Coming King.',
    foundationHistory: 'Our Foundation & History',
    foundationHistorySub: 'Founded in 1923 by Aimee Semple McPherson, the Foursquare movement began with the opening of Angelus Temple in Los Angeles. Sister Aimee was a pioneer in using modern technology and creative arts to share the Gospel, a legacy we continue today.',
    founder: 'Founder',
    established: 'Established',
    savior: 'Savior',
    saviorDesc: 'Jesus is our Savior',
    baptizer: 'Baptizer',
    baptizerDesc: 'With the Holy Spirit',
    healer: 'Healer',
    healerDesc: 'Jesus is our Healer',
    comingKing: 'Coming King',
    comingKingDesc: 'He is coming again',
    globalFamily: 'We are a global family of over 8 million members in 140+ countries, united by our passion for the Great Commission and our commitment to interdenominational cooperation.',
    ourMission: 'Our Mission',
    ourMissionSub: 'To present the Foursquare Gospel to every person in every land, making disciples who make disciples.',
    deepStudy: 'Deep Study',
    scrollToExplore: 'Scroll to Explore',
    nextService: 'Next Service',
    sundayMorning: 'Sunday Morning',
    mainSanctuary: 'Main Sanctuary',
    studySessions: 'Study Sessions',
    studySessionsSub: 'Join our rigorous academic and spiritual journey through the living Word of God.',
    deepExegesis: 'Deep Exegesis',
    deepExegesisSub: 'A verse-by-verse analytical study of the scriptures, focusing on original languages and historical context.',
    theologicalSeminar: 'Theological Seminar',
    theologicalSeminarSub: 'Advanced discussions on systematic theology, church history, and apologetics for the modern believer.',
    hermeneuticsWorkshop: 'Hermeneutics Workshop',
    hermeneuticsWorkshopSub: 'Practical training in the art and science of biblical interpretation and sermon preparation.',
    propheticInsight: 'Prophetic Insight',
    propheticInsightSub: 'Exploring the prophetic books of the Bible and their relevance to current world events.',
    studyQuote: '"Study to shew thyself approved unto God, a workman that needeth not to be ashamed."',
    worshipQuote: '"Where two or three are gathered in my name, there am I among them."',
    studySessionsDesc: 'Our study sessions are designed to challenge your intellect and nourish your spirit. Every session is a step deeper into the infinite wisdom of the scriptures.',
    worshipSessionsDesc: "Every service is a unique opportunity to encounter God's presence and grow in community. Whether you're joining us for the first time or the hundredth, there's a place for you here.",
    enrollInSession: 'Enroll in Session',
    planYourVisit: 'Plan Your Visit',
    viewCurriculum: 'View Curriculum',
    watchPastServices: 'Watch Past Services',
    ourSchools: 'Our Schools',
    ourSchoolsSub: 'CityLight Church is proud to run nursery and primary schools in four different areas within Rwanda. We believe in providing quality education rooted in Christian values to build a brighter future for our children.',
    ourMinistrySub: 'Our ministry extends beyond the church walls. We are engaged in leadership training, social development, and economic projects that support both national and local communities.',
    leadership: 'Leadership',
    leadershipSub: 'Continuous training for capacity building.',
    development: 'Development',
    developmentSub: 'Social activities and economic projects.',
    wordStudy: 'Word Study',
    wordArchive: 'Word Archive',
    philosophy: 'Philosophy',
    ourHistory: 'Our History',
    ourValues: 'Our Values',
    generalInfo: 'General Info',
    mainServices: 'Main Services',
    sermons: 'Sermons',
    resources: 'Resources',
    ourSchool: 'Our School',
    selectLanguage: 'Select Language',
    aiPoweredTranslation: 'AI Powered Translation',
    unmuteVoice: 'Unmute Voice',
    muteVoice: 'Mute Voice',
    switchToLightMode: 'Switch to Light Mode',
    switchToDarkMode: 'Switch to Dark Mode',
    churchKnowledgeQuiz: 'Church Knowledge Quiz',
    christianMember: 'Christian Member',
    visitor: 'Visitor',
    heritageScore: 'Heritage Score',
    from: 'From',
    fromChurch: 'From Church',
    yes: 'Yes',
    no: 'No',
    unmute: 'Unmute',
    mute: 'Mute',
    footerDesc: 'A community of faith dedicated to loving God and loving our neighbors. Join us as we journey together in faith.',
    quickLinks: 'Quick Links',
    contactInfo: 'Contact Info',
    newsletter: 'Newsletter',
    newsletterSub: 'Stay updated with our weekly news and events.',
    emailPlaceholder: 'Your email address',
    subscribe: 'Subscribe',
    allRightsReserved: 'All rights reserved.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    registrationPlaceholderName: 'e.g. John Doe',
    registrationPlaceholderFamily: 'e.g. The Smith Family',
    registrationPlaceholderMember: 'Member',
    registrationPlaceholderPrevious: 'e.g. Angelus Temple',
    quizTitle: 'Church Knowledge',
    quizSub: 'Test your Foursquare heritage',
    quizQuestion: 'Question',
    quizOf: 'of',
    quizExcellent: 'Excellent Knowledge!',
    quizKeepLearning: 'Keep Learning!',
    quizScored: 'You scored',
    quizOutOf: 'out of',
    quizPassedDesc: 'You have a strong understanding of our church\'s heritage. You are officially recognized as a \'Knowledgeable Visitor\'!',
    quizFailedDesc: 'Our heritage is rich and deep. We encourage you to explore the \'About\' section to learn more about our four-fold ministry.',
    tryAgain: 'Try Again',
    finish: 'Finish',
    quizQ1: 'Who founded the Foursquare Gospel Church?',
    quizQ1O1: 'John Wesley',
    quizQ1O2: 'Aimee Semple McPherson',
    quizQ1O3: 'Billy Graham',
    quizQ1O4: 'Martin Luther',
    quizQ2: 'What does the \'Foursquare\' represent?',
    quizQ2O1: 'Four Seasons',
    quizQ2O2: 'Four Gospels',
    quizQ2O3: 'Four-fold ministry of Jesus',
    quizQ2O4: 'Four Directions',
    quizQ3: 'Which of these is NOT one of the four pillars?',
    quizQ3O1: 'Savior',
    quizQ3O2: 'Baptizer',
    quizQ3O3: 'Healer',
    quizQ3O4: 'Prophet',
    quizQ4: 'In what year was the Foursquare movement founded?',
    quizQ4O1: '1900',
    quizQ4O2: '1923',
    quizQ4O3: '1950',
    quizQ4O4: '1880',
    wordAccount: 'Word Account',
    overview: 'Overview',
    myStudies: 'My Studies',
    studyNotes: 'Study Notes',
    settings: 'Settings',
    close: 'Close',
    spiritualGrowth: 'Spiritual Growth',
    myBibleStudies: 'My Bible Studies',
    personalNotes: 'Personal Notes',
    trackingJourney: 'Tracking your journey through the Word.',
    levelDisciple: 'Level 12 Disciple',
    chaptersRead: 'Chapters Read',
    studiesCompleted: 'Studies Completed',
    prayerStreak: 'Prayer Streak',
    savedVerses: 'Saved Verses',
    recentProgress: 'Recent Progress',
    viewAll: 'View All',
    lastAccessed: 'Last accessed',
    continueJourney: 'Continue Your Journey',
    continueJourneySub: 'You\'re only 3 chapters away from completing the "Genesis" study guide!',
    resumeStudy: 'Resume Study',
    enrollNewStudy: 'Enroll in New Study',
    readFullNote: 'Read Full Note',
    days: 'Days',
    hours: 'Hours',
    ago: 'ago',
    day: 'day',
    today: 'Today',
    yesterday: 'Yesterday',
    completed: 'Completed',
    inProgress: 'In Progress',
    studySubText: 'Comprehensive study of the scriptures.',
    studyGenesis: 'Genesis: The Beginning',
    studyRomans: 'Romans: Foundations of Faith',
    studyParables: 'The Parables of Jesus',
    note1Title: 'Reflections on Grace',
    note1Preview: 'Grace is not just unmerited favor, it\'s the power of God to transform...',
    note2Title: 'Sermon Notes: The Light',
    note2Preview: 'Walking in the light means living in transparency and truth...',
    note3Title: 'Questions for Pastor',
    note3Preview: '1. How do we interpret the cultural context of 1 Corinthians?',
  },
  ES: {
    home: 'Inicio',
    live: 'En Vivo',
    services: 'Servicios',
    bibleStudy: 'Estudio Bíblico',
    gallery: 'Galería',
    branches: 'Sedes',
    aboutUs: 'Nosotros',
    register: 'Registrarse',
    give: 'Dar',
    media: 'Medios',
    videoSermons: 'Sermones en Video',
    photoGallery: 'Galería de Fotos',
    registrationTitle: 'Registro de la Iglesia',
    registrationSub: 'Únete a nuestra familia hoy',
    individual: 'Individual',
    family: 'Familia',
    fullName: 'Nombre Completo',
    familyName: 'Nombre de la Familia',
    addMember: 'Agregar Miembro',
    familyMembers: 'Miembros de la Familia',
    visitedBefore: '¿Has visitado Grace Community antes?',
    yesVisited: 'Sí, lo he hecho',
    noVisited: 'No, primera vez',
    completeRegistration: 'Completar Registro',
    dailyDevotional: 'Devocional Diario',
    startDayGrace: 'Comienza tu día con Gracia',
    devotionalSub: 'Haz clic abajo para generar un devocional único impulsado por IA para inspirar tu caminar con Dios hoy.',
    generateDevotional: 'Generar Devocional de Hoy',
    preparingInspiration: 'Preparando tu inspiración...',
    reflection: 'Reflexión',
    prayer: 'Oración',
    generateAnother: 'Generar Otro',
    bibleStudyGroups: 'Grupos de Estudio Bíblico',
    bibleStudySub: 'Profundiza tu comprensión de las Escrituras y construye amistades duraderas en nuestros estudios bíblicos.',
    viewAllGroups: 'Ver Todos los Grupos',
    scriptureLibrary: 'Biblioteca de Versículos',
    scriptureLibrarySub: 'Accede a nuestra colección de versículos bíblicos para cada situación. Descarga y comparte estas palabras de vida.',
    exploreScriptures: 'Explorar Escrituras',
    branchDetails: 'Detalles de la Sede',
    pastor: 'Pastor',
    serviceTimes: 'Horarios de Servicio',
    aboutBranch: 'Sobre esta Sede',
    mission: 'Nuestra Misión',
    history: 'Nuestra Historia',
    worshippers: 'Adoradores',
    contactUs: 'Contáctanos',
    scriptureLibraryTitle: 'Biblioteca de Escrituras',
    scriptureLibrarySubText: 'Explora palabras directas de la Biblia categorizadas para tu viaje de vida.',
    printFlyer: 'Imprimir Volante',
    peaceComfort: 'Paz y Consuelo',
    strengthCourage: 'Fuerza y Coraje',
    hopeFuture: 'Esperanza y Futuro',
    ourServices: 'Nuestros Servicios',
    servicesSub: 'Ofrecemos varias formas de conectarte con Dios y nuestra comunidad durante la semana.',
    sundayWorship: 'Adoración del Domingo',
    midWeekPrayer: 'Oración de Mitad de Semana',
    youthGathering: 'Reunión de Jóvenes',
    communityOutreach: 'Alcance Comunitario',
    welcome: 'Bienvenido a Grace Community',
    heroTitle: 'Vive la Gracia, Encuentra Comunidad',
    heroSub: 'Un lugar donde la fe se encuentra con el compañerismo. Únete a nosotros mientras crecemos juntos en Cristo.',
    joinLive: 'Unirse en Vivo',
    viewServices: 'Ver Servicios',
    liveNow: 'En Vivo Ahora',
    onlineService: 'Únete a nuestro Servicio en Línea',
    watching: 'Viendo',
    upcomingStreams: 'Próximas Transmisiones',
    ourBranches: 'Nuestras Sedes',
    findBranch: 'Encuentra una sede de Grace Community cerca de ti.',
    churchGallery: 'Galería de la Iglesia',
    capturingMoments: 'Capturando momentos de fe, compañerismo y servicio.',
    heritage: 'Nuestra Herencia',
    foursquareTitle: 'Iglesia del Evangelio Cuadrangular',
    getInvolved: 'Formas de Participar',
    wantToBeChristian: '¿Quieres ser miembro de la fe cristiana?',
    previousChurch: '¿De qué iglesia vienes?',
    yesMember: 'Sí, quiero unirme',
    noMember: 'Aún no',
    voiceTranslation: 'Traducción de Voz',
    enableTranslation: 'Activar Traducción en Vivo',
    translating: 'Traduciendo...',
    translationNotice: 'Traducción en tiempo real impulsada por IA para nuestra familia global.',
    watchOnYoutube: 'Ver en YouTube',
    mediaExplorer: 'Explorador de Medios',
    recentSermons: 'Sermones Recientes',
    photoHighlights: 'Fotos Destacadas',
    watchNow: 'Ver Ahora',
    viewGallery: 'Ver Galería',
    unmute: 'Activar sonido',
    mute: 'Silenciar',
    theLivingWord: 'La Palabra Viva',
    livingWordSub: '"En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios."',
    ourPhilosophy: 'Nuestra Filosofía',
    illuminatingTruth: 'Iluminando la Verdad',
    biblicalExcellence: 'Excelencia Bíblica',
    biblicalExcellenceSub: 'Creemos en el estudio meticuloso de las escrituras, buscando la intención original y la aplicación eterna del mensaje de Dios.',
    communityScholars: 'Comunidad de Eruditos',
    communityScholarsSub: 'Word Light no es solo una iglesia; es una comunidad de creyentes que también son estudiantes de la Palabra, creciendo juntos en sabiduría y gracia.',
    aiScriptureInsight: 'Perspectiva Bíblica de IA',
    aiScriptureInsightSub: 'Pide a la IA una perspectiva teológica profunda sobre el estudio de hoy...',
    foursquareDesc: 'Grace Community es un orgulloso miembro de la Iglesia Internacional del Evangelio Cuadrangular. El término "Cuadrangular" representa el ministerio cuádruple de Jesucristo como Salvador, Bautizador con el Espíritu Santo, Sanador y Rey que Viene.',
    foundationHistory: 'Nuestra Fundación e Historia',
    foundationHistorySub: 'Fundada en 1923 por Aimee Semple McPherson, el movimiento Cuadrangular comenzó con la apertura del Templo Angelus en Los Ángeles. La hermana Aimee fue pionera en el uso de tecnología moderna y artes creativas para compartir el Evangelio, un legado que continuamos hoy.',
    founder: 'Fundadora',
    established: 'Establecida',
    savior: 'Salvador',
    saviorDesc: 'Jesús es nuestro Salvador',
    baptizer: 'Bautizador',
    baptizerDesc: 'Con el Espíritu Santo',
    healer: 'Sanador',
    healerDesc: 'Jesús es nuestro Sanador',
    comingKing: 'Rey que Viene',
    comingKingDesc: 'Él vendrá otra vez',
    globalFamily: 'Somos una familia global de más de 8 millones de miembros en más de 140 países, unidos por nuestra pasión por la Gran Comisión y nuestro compromiso con la cooperación interdenominacional.',
    ourMission: 'Nuestra Misión',
    ourMissionSub: 'Presentar el Evangelio Cuadrangular a cada persona en cada tierra, haciendo discípulos que hagan discípulos.',
    deepStudy: 'Estudio Profundo',
    listen: 'Escuchar',
    scrollToExplore: 'Desliza para Explorar',
    nextService: 'Próximo Servicio',
    sundayMorning: 'Domingo por la Mañana',
    mainSanctuary: 'Santuario Principal',
    studySessions: 'Sesiones de Estudio',
    studySessionsSub: 'Únete a nuestro riguroso viaje académico y espiritual a través de la Palabra viva de Dios.',
    deepExegesis: 'Exégesis Profunda',
    deepExegesisSub: 'Un estudio analítico verso por verso de las escrituras, centrado en los idiomas originales y el contexto histórico.',
    theologicalSeminar: 'Seminario Teológico',
    theologicalSeminarSub: 'Discusiones avanzadas sobre teología sistemática, historia de la iglesia y apologética para el creyente moderno.',
    hermeneuticsWorkshop: 'Taller de Hermenéutica',
    hermeneuticsWorkshopSub: 'Capacitación práctica en el arte y la ciencia de la interpretación bíblica y la preparación de sermones.',
    propheticInsight: 'Perspectiva Profética',
    propheticInsightSub: 'Explorando los libros proféticos de la Biblia y su relevancia para los eventos mundiales actuales.',
    studyQuote: '"Procura con diligencia presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse."',
    worshipQuote: '"Donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos."',
    studySessionsDesc: 'Nuestras sesiones de estudio están diseñadas para desafiar tu intelecto y nutrir tu espíritu. Cada sesión es un paso más profundo en la sabiduría infinita de las escrituras.',
    worshipSessionsDesc: 'Cada servicio es una oportunidad única para encontrar la presencia de Dios y crecer en comunidad. Ya sea que nos acompañes por primera vez o por centésima vez, hay un lugar para ti aquí.',
    enrollInSession: 'Inscribirse en la Sesión',
    planYourVisit: 'Planifica tu Visita',
    viewCurriculum: 'Ver Currículo',
    watchPastServices: 'Ver Servicios Pasados',
    ourSchools: 'Nuestras Escuelas',
    ourSchoolsSub: 'La Iglesia CityLight se enorgullece de dirigir escuelas infantiles y primarias en cuatro áreas diferentes de Ruanda. Creemos en proporcionar una educación de calidad arraigada en los valores cristianos para construir un futuro mejor para nuestros niños.',
    ourMinistry: 'Nuestro Ministerio',
    ourMinistrySub: 'Nuestro ministerio se extiende más allá de los muros de la iglesia. Estamos comprometidos con la capacitación de liderazgo, el desarrollo social y los proyectos económicos que apoyan a las comunidades nacionales y locales.',
    leadership: 'Liderazgo',
    leadershipSub: 'Capacitación continua para el desarrollo de capacidades.',
    development: 'Desarrollo',
    developmentSub: 'Actividades sociales y proyectos económicos.',
    wordStudy: 'Estudio de la Palabra',
    wordArchive: 'Archivo de la Palabra',
    philosophy: 'Filosofía',
    ourHistory: 'Nuestra Historia',
    ourValues: 'Nuestros Valores',
    generalInfo: 'Información General',
    mainServices: 'Servicios Principales',
    sermons: 'Sermones',
    resources: 'Recursos',
    ourSchool: 'Nuestra Escuela',
    ourMinistryNav: 'Nuestro Ministerio',
    selectLanguage: 'Seleccionar Idioma',
    aiPoweredTranslation: 'Traducción con IA',
    unmuteVoice: 'Activar Voz',
    muteVoice: 'Silenciar Voz',
    switchToLightMode: 'Cambiar a Modo Claro',
    switchToDarkMode: 'Cambiar a Modo Oscuro',
    churchKnowledgeQuiz: 'Prueba de Conocimientos de la Iglesia',
    christianMember: 'Miembro Cristiano',
    visitor: 'Visitante',
    heritageScore: 'Puntaje de Herencia',
    from: 'De',
    fromChurch: 'De la Iglesia',
    yes: 'Sí',
    no: 'No',
    unmuteNav: 'Activar',
    muteNav: 'Silenciar',
    footerDesc: 'Una comunidad de fe dedicada a amar a Dios y amar a nuestros prójimos. Únete a nosotros mientras caminamos juntos en la fe.',
    quickLinks: 'Enlaces Rápidos',
    contactInfo: 'Información de Contacto',
    newsletter: 'Boletín Informativo',
    newsletterSub: 'Mantente actualizado con nuestras noticias y eventos semanales.',
    emailPlaceholder: 'Tu dirección de correo electrónico',
    subscribe: 'Suscribirse',
    allRightsReserved: 'Todos los derechos reservados.',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    registrationPlaceholderName: 'p. ej. Juan Pérez',
    registrationPlaceholderFamily: 'p. ej. La Familia Smith',
    registrationPlaceholderMember: 'Miembro',
    registrationPlaceholderPrevious: 'p. ej. Templo Angelus',
    quizTitle: 'Conocimiento de la Iglesia',
    quizSub: 'Pon a prueba tu herencia Foursquare',
    quizQuestion: 'Pregunta',
    quizOf: 'de',
    quizExcellent: '¡Excelente Conocimiento!',
    quizKeepLearning: '¡Sigue Aprendiendo!',
    quizScored: 'Obtuviste',
    quizOutOf: 'de',
    quizPassedDesc: 'Tienes un sólido entendimiento de la herencia de nuestra iglesia. ¡Eres oficialmente reconocido como un \'Visitante Conocedor\'!',
    quizFailedDesc: 'Nuestra herencia es rica y profunda. Te animamos a explorar la sección \'Acerca de\' para aprender más sobre nuestro ministerio cuádruple.',
    tryAgain: 'Intentar de Nuevo',
    finish: 'Finalizar',
    quizQ1: '¿Quién fundó la Iglesia del Evangelio Foursquare?',
    quizQ1O1: 'John Wesley',
    quizQ1O2: 'Aimee Semple McPherson',
    quizQ1O3: 'Billy Graham',
    quizQ1O4: 'Martín Lutero',
    quizQ2: '¿Qué representa el \'Foursquare\'?',
    quizQ2O1: 'Cuatro Estaciones',
    quizQ2O2: 'Cuatro Evangelios',
    quizQ2O3: 'Ministerio cuádruple de Jesús',
    quizQ2O4: 'Cuatro Direcciones',
    quizQ3: '¿Cuál de estos NO es uno de los cuatro pilares?',
    quizQ3O1: 'Salvador',
    quizQ3O2: 'Bautizador',
    quizQ3O3: 'Sanador',
    quizQ3O4: 'Profeta',
    quizQ4: '¿En qué año se fundó el movimiento Foursquare?',
    quizQ4O1: '1900',
    quizQ4O2: '1923',
    quizQ4O3: '1950',
    quizQ4O4: '1880',
    wordAccount: 'Cuenta de la Palabra',
    overview: 'Resumen',
    myStudies: 'Mis Estudios',
    studyNotes: 'Notas de Estudio',
    settings: 'Ajustes',
    close: 'Cerrar',
    spiritualGrowth: 'Crecimiento Espiritual',
    myBibleStudies: 'Mis Estudios Bíblicos',
    personalNotes: 'Notas Personales',
    trackingJourney: 'Siguiendo tu viaje a través de la Palabra.',
    levelDisciple: 'Discípulo Nivel 12',
    chaptersRead: 'Capítulos Leídos',
    studiesCompleted: 'Estudios Completados',
    prayerStreak: 'Racha de Oración',
    savedVerses: 'Versículos Guardados',
    recentProgress: 'Progreso Reciente',
    viewAll: 'Ver Todo',
    lastAccessed: 'Último acceso',
    continueJourney: 'Continúa tu Viaje',
    continueJourneySub: '¡Estás a solo 3 capítulos de completar la guía de estudio de "Génesis"!',
    resumeStudy: 'Reanudar Estudio',
    enrollNewStudy: 'Inscribirse en Nuevo Estudio',
    readFullNote: 'Leer Nota Completa',
    days: 'Días',
    hours: 'Horas',
    ago: 'hace',
    day: 'día',
    today: 'Hoy',
    yesterday: 'Ayer',
    completed: 'Completado',
    inProgress: 'En Progreso',
    studySubText: 'Estudio exhaustivo de las escrituras.',
    studyGenesis: 'Génesis: El Principio',
    studyRomans: 'Romanos: Fundamentos de la Fe',
    studyParables: 'Las Parábolas de Jesús',
    note1Title: 'Reflexiones sobre la Gracia',
    note1Preview: 'La gracia no es solo un favor inmerecido, es el poder de Dios para transformar...',
    note2Title: 'Notas del Sermón: La Luz',
    note2Preview: 'Caminar en la luz significa vivir en transparencia y verdad...',
    note3Title: 'Preguntas para el Pastor',
    note3Preview: '1. ¿Cómo interpretamos el contexto cultural de 1 Corintios?',
  },
  KIN: {
    home: 'Ahabanza',
    live: 'Live',
    services: 'Amateraniro',
    bibleStudy: 'K. Bibiliya',
    gallery: 'Amafoto',
    branches: 'Amashami',
    aboutUs: 'Abo turi',
    register: 'Kwiyandikisha',
    give: 'Gutanga',
    media: 'Ibinyamakuru',
    videoSermons: 'Inyigisho za Video',
    photoGallery: 'Ububiko bw\'Amafoto',
    registrationTitle: 'Kwiyandikisha mu Itorero',
    registrationSub: 'Injira mu muryango wacu uyu munsi',
    individual: 'Umuntu umwe',
    family: 'Umuryango',
    fullName: 'Amazina yose',
    familyName: 'Izina ry\'umuryango',
    addMember: 'Ongeramo umunyamuryango',
    familyMembers: 'Abagize umuryango',
    visitedBefore: 'Waba warigeze gusura Grace Community mbere?',
    yesVisited: 'Yego, narahasuye',
    noVisited: 'Oya, ni ubwa mbere',
    completeRegistration: 'Uzuza kwiyandikisha',
    dailyDevotional: 'Inyigisho y\'Umunsi',
    startDayGrace: 'Tangira Umunsi n\'Ubuntu',
    devotionalSub: 'Kanda hano hasi kugira ngo ubone inyigisho yihariye ikozwe n\'ubuhanga buhangano (AI) igufasha mu rugendo rwawe n\'Imana uyu munsi.',
    generateDevotional: 'Bona Inyigisho y\'Uyu Munsi',
    preparingInspiration: 'Turimo gutegura inyigisho yawe...',
    reflection: 'Guzirikana',
    prayer: 'Isengesho',
    generateAnother: 'Bona Indi Nyigisho',
    bibleStudyGroups: 'Amatsinda yo Kwiga Bibiliya',
    bibleStudySub: 'Syura ubumenyi bwawe bw\'Ibyanditswe Byera kandi wubake ubucuti burambye mu matsinda yacu mato yo kwiga Bibiliya. Dufite amatsinda ya buri wese.',
    viewAllGroups: 'Reba Amatsinda Yose',
    scriptureLibrary: 'Ububiko bw\'Ibyanditswe',
    scriptureLibrarySub: 'Gera ku byanditswe bya Bibiliya byatoranyijwe kuri buri mimerere. Manura kandi usangize abandi aya magambo y\'ubuzima.',
    exploreScriptures: 'Shaka Ibyanditswe',
    branchDetails: 'Ibisobanuro by\'Ishami',
    pastor: 'Pasiteri',
    serviceTimes: 'Igihe cy\'Amateraniro',
    aboutBranch: 'Ibyerekeye iri Shami',
    mission: 'Inshingano zacu',
    history: 'Amateka yacu',
    worshippers: 'Abasenga',
    contactUs: 'Twandikire',
    scriptureLibraryTitle: 'Ububiko bw\'Ibyanditswe',
    scriptureLibrarySubText: 'Shaka amagambo ya Bibiliya yatoranyijwe kuri buri rugendo rw\'ubuzima bwawe. Manura ifoto nziza y\'umurongo ukunda kugira ngo uyigumane cyangwa uyisangize abandi.',
    printFlyer: 'Printa Ifoto',
    peaceComfort: 'Amahoro n\'Ihumure',
    strengthCourage: 'Imbaraga n\'Ubutwari',
    hopeFuture: 'Ibyiringiro n\'Ejo Hazaza',
    ourServices: 'Serivisi Zacu',
    servicesSub: 'Dutanga uburyo butandukanye bwo guhura n\'Imana n\'umuryango wacu mu cyumweru cyose. Twifatanye muri rimwe mu materaniro yacu yateguwe.',
    sundayWorship: 'Gusenga ku Cyumweru mu Gitondo',
    midWeekPrayer: 'Isengesho ryo mu Cyumweru hagati',
    youthGathering: 'Iteraniro ry\'Urubyiruko',
    communityOutreach: 'Gufasha Umuryango',
    welcome: 'Ikaze muri Grace Community',
    heroTitle: 'Sogongera Ubuntu, Gira Umuryango',
    heroSub: 'Ahantu ukwizera guhurira n\'ubusabane. Twifatanye mu gukura muri Kristo.',
    joinLive: 'Kurikira Live',
    viewServices: 'Reba Amateraniro',
    liveNow: 'Ubu riraba',
    onlineService: 'Kurikira Amateraniro kuri Interineti',
    watching: 'Abakurikiye',
    upcomingStreams: 'Amateraniro ataha',
    ourBranches: 'Amashami yacu',
    findBranch: 'Shaka ishami rya Grace Community riri hafi yawe wifatanye n\'umuryango wacu.',
    churchGallery: 'Ububiko bw\'Amafoto',
    capturingMoments: 'Gufata ibihe by\'ukwizera, ubusabane, n\'umurimo.',
    heritage: 'Umurage wacu',
    foursquareTitle: 'Itorero rya Foursquare Gospel',
    getInvolved: 'Uburyo bwo kwifatanya natwe',
    wantToBeChristian: 'Waba wifuza kuba umukirisitu cyangwa umunyamuryango w\'itorero?',
    previousChurch: 'Waturutse mu rthe torero?',
    yesMember: 'Yego, ndabyifuza',
    noMember: 'Oya, mbanje kubitekerezaho',
    voiceTranslation: 'Guhindura mu Majwi',
    enableTranslation: 'Gufungura Guhindura Live',
    translating: 'Turimo guhindura...',
    translationNotice: 'Guhindura mu buryo bwa ako kanya bikozwe na AI ku muryango wacu mugari.',
    watchOnYoutube: 'Reba kuri YouTube',
    mediaExplorer: 'Ubushakashatsi bw\'Ibinyamakuru',
    recentSermons: 'Inyigisho za vuba',
    photoHighlights: 'Amafoto y\'ingenzi',
    watchNow: 'Reba ubu',
    viewGallery: 'Reba amafoto',
    ourMinistries: 'Minisiteri Zacu',
    ministriesSub: 'Shaka uburyo butandukanye dukorera umuryango wacu kandi tugakurira hamwe muri Kristo binyuze mu matsinda yacu ya minisiteri yitanga.',
    childrensMinistry: "Minisiteri y'Abana",
    youthMinistry: "Minisiteri y'Urubyiruko",
    evangelismMinistry: "Minisiteri y'Ivugabutumwa",
    eduLeadershipMinistry: "Inyigisho za Gikristo & Ubuyobozi",
    mercyMinistry: "Minisiteri y'Imbabazi",
    counselingMinistry: "Minisiteri y'Inama",
    learnMoreJoin: 'Menya Byinshi & Injira',
    ministryImpact: 'Umurimo wa Minisiteri mu ncamake',
    ministryName: 'Izina rya Minisiteri',
    focusArea: 'Icyo yibandaho',
    meetingFreq: 'Inshuro bahura',
    status: 'Imimerere',
    active: 'Irakora',
    sermonsResources: 'Inyigisho & Ibikoresho',
    sermonsSub: 'Gaburira ubugingo bwawe inyigisho nshya n\'ibikoresho byo kwiga.',
    latestSermons: 'Inyigisho nshya',
    watch: 'Reba',
    listen: 'Umva',
    studyResources: 'Ibikoresho byo Kwiga',
    download: 'Manura',
    viewAllSermons: 'Reba Inyigisho Zose',
    viewAllResources: 'Reba Ibikoresho Byose',
    deeperWord: 'Syura ubumenyi bw\'Ijambo',
    inductiveStudy: 'Kwiga mu buryo bw\'Inductive',
    topicalStudy: 'Kwiga ku ngingo runaka',
    characterStudy: 'Kwiga ku muntu runaka',
    devotionalStudy: 'Kwiga mu buryo bwa Devotional',
    viewStudyDetails: 'Reba Ibisobanuro',
    joinThisGroup: 'Injira muri iri tsinda',
    downloadStudyGuide: 'Manura Igitabo cyo Kwiga',
    theLivingWord: 'Ijambo Rizima',
    livingWordSub: '"Mu ntangiriro hariho Ijambo, kandi iryo Jambo ryari kwa Mana, kandi iryo Jambo ryari Imana."',
    ourPhilosophy: 'Imitekerereze yacu',
    illuminatingTruth: 'Kumurika Ukuri',
    biblicalExcellence: 'Ubuhamya bwa Bibiliya',
    biblicalExcellenceSub: "Twemera kwiga Ibyanditswe byera mu buryo bwitondewe, dushaka intego y'umwimerere n'uburyo bwo gushyira mu bikorwa ubutumwa bw'Imana mu bihe byose.",
    communityScholars: 'Umuryango w\'Abigishwa',
    communityScholarsSub: "Word Light si itorero gusa; ni umuryango w'abizera ari n'abigishwa b'Ijambo, bakurira hamwe mu bwenge no mu buntu.",
    aiScriptureInsight: 'Ubumenyi bwa AI ku Byanditswe',
    aiScriptureInsightSub: "Saba AI ubumenyi bwimbitse bwa tewolojiya ku nyigisho y'uyu munsi...",
    foursquareDesc: 'Grace Community ni umunyamuryango w\'itorero mpuzamahanga rya Foursquare Gospel. Ijambo "Foursquare" rigereranya umurimo w\'uburyo bune wa Yesu Kristo nka Umukiza, Umubatizesha Umwuka Wera, Umukiza w\'indwara, n\'Umwami ugiye kuza.',
    foundationHistory: 'Urwego rwacu & Amateka',
    foundationHistorySub: 'Ryashinzwe mu 1923 na Aimee Semple McPherson, umuryango wa Foursquare watangiriye ku gufungura Urusengero rwa Angelus i Los Angeles. Mushiki wacu Aimee yari umupayiniya mu gukoresha ikoranabuhanga rigezweho n\'ubuhanzi mu gusangira ubutumwa bwiza, umurage dukomeza na n\'ubu.',
    founder: 'Uwaryashinze',
    established: 'Ryashinzwe',
    savior: 'Umukiza',
    saviorDesc: 'Yesu ni Umukiza wacu',
    baptizer: 'Umubatiza',
    baptizerDesc: 'N\'Umwuka Wera',
    healer: 'Umukiza w\'indwara',
    healerDesc: 'Yesu ni Umukiza wacu w\'indwara',
    comingKing: 'Umwami ugiye kuza',
    comingKingDesc: 'Azagaruka vuba',
    globalFamily: 'Turi umuryango mugari w\'abanyamuryango barenga miliyoni 8 mu bihugu birenga 140, bunze ubumwe n\'ishyaka ryacu ryo gusohoza Inshingano Nkuru n\'ubushake bwacu bwo gukorana n\'andi matorero.',
    ourMission: 'Inshingano yacu',
    ourMissionSub: 'Kugeza ubutumwa bwiza bwa Foursquare ku muntu wese mu gihugu cyose, tugahindura abantu abigishwa nabo bakahindura abandi.',
    deepStudy: 'Kwiga Byimbitse',
    scrollToExplore: 'Manuka ushake ibindi',
    nextService: 'Amateraniro ataha',
    sundayMorning: 'Ku Cyumweru mu gitondo',
    mainSanctuary: 'Mu rusengero rwagati',
    studySessions: 'Ibiganiro byo Kwiga',
    studySessionsSub: 'Injira mu rugendo rwacu rw\'ubumenyi n\'umwuka binyuze mu Jambo rizima ry\'Imana.',
    deepExegesis: 'Gusesengura Byimbitse',
    deepExegesisSub: 'Kwiga Ibyanditswe umurongo ku wundi, twibanda ku ndimi z\'umwimerere n\'amateka.',
    theologicalSeminar: 'Ihugurwa rya Tewolojiya',
    theologicalSeminarSub: 'Ibiganiro byateye imbere kuri tewolojiya, amateka y\'itorero, n\'ubwirinzi bw\'ukuri ku mwizera ugezweho.',
    hermeneuticsWorkshop: 'Amahugurwa ya Hermeneutics',
    hermeneuticsWorkshopSub: 'Ihugurwa ngiro mu buhanga bwo gusobanura Bibiliya no gutegura inyigisho.',
    propheticInsight: 'Ubumenyi bw\'Ubuhanuzi',
    propheticInsightSub: 'Gushakashaka mu bitabo by\'ubuhanuzi bya Bibiliya n\'akamaro kabyo mu bintu bibaho mu isi uyu munsi.',
    studyQuote: '"Gira umwete wo kwiyerekana imbere y\'Imana nk\'ushimwa, umukozi udakwiriye kugira isoni."',
    worshipQuote: '"Aho babiri cyangwa batatu bateraniye mu izina ryanjye, nanjye mba ndi hagati yabo."',
    studySessionsDesc: 'Ibiganiro byacu byo kwiga byateguwe kugira ngo bibyutse ubwenge bwawe kandi bigaburire umwuka wawe. Buri kiganiro ni intambwe ijya mbere mu bwenge butagira iherezo bw\'Ibyanditswe.',
    worshipSessionsDesc: 'Buri teraniro ni amahirwe yihariye yo guhura n\'Imana no gukurira mu muryango. Waba uje bwa mbere cyangwa bwa ijana, hari umwanya wawe hano.',
    enrollInSession: 'Iyandikishe mu kiganiro',
    planYourVisit: 'Tegura gusura kwacu',
    viewCurriculum: 'Reba integanyanyigisho',
    watchPastServices: 'Reba amateraniro yashize',
    ourSchools: 'Amashuri yacu',
    ourSchoolsSub: 'Itorero rya CityLight rifite ishema ryo kuyobora amashuri y\'incuke n\'abanza mu bice bine bitandukanye mu Rwanda. Twemera gutanga uburezi bufite ireme bushingiye ku ndangagaciro za Gikristo kugira ngo twubake ejo hazaza heza h\'abana bacu.',
    ourMinistrySub: 'Umurimo wacu urenga inkuta z\'urusengero. Twishora mu mahugurwa y\'ubuyobozi, iterambere ry\'imibereho, n\'imishinga y\'ubukungu ishyigikira imiryango yaba iy\'igihugu n\'iy\'ibanze.',
    leadership: 'Ubuyobozi',
    leadershipSub: 'Amahugurwa ahoraho yo kubaka ubushobozi.',
    development: 'Iterambere',
    developmentSub: 'Ibikorwa by\'imibereho n\'imishinga y\'ubukungu.',
    wordStudy: 'Kwiga Ijambo',
    wordArchive: 'Ububiko bw\'Ijambo',
    philosophy: 'Imitekerereze',
    ourHistory: 'Amateka yacu',
    ourValues: 'Indangagaciro zacu',
    generalInfo: 'Amakuru rusange',
    mainServices: 'Amateraniro makuru',
    sermons: 'Inyigisho',
    resources: 'Ibikoresho',
    ourSchool: 'Ishuri ryacu',
    selectLanguage: 'Hitamo Ururimi',
    aiPoweredTranslation: 'Ubuhinduzi bukoresha AI',
    unmuteVoice: 'Kura mu mucece',
    muteVoice: 'Shyira mu mucece',
    switchToLightMode: 'Shyira mu mucyo',
    switchToDarkMode: 'Shyira mu mwijima',
    churchKnowledgeQuiz: 'Ikizamini cy\'ubumenyi bw\'itorero',
    christianMember: 'Umukristo',
    visitor: 'Umushyitsi',
    heritageScore: 'Amanota y\'amateka',
    from: 'Kuva',
    fromChurch: 'Kuva mu itorero',
    yes: 'Yego',
    no: 'Oya',
    unmuteNav: 'Kura mu mucece',
    muteNav: 'Shyira mu mucece',
    footerDesc: 'Umuryango w\'ukwizera wiyemeje gukunda Imana no gukunda bagenzi bacu. Twifatanye mu rugendo rwacu rw\'ukwizera.',
    quickLinks: 'Ihuza ryihuse',
    contactInfo: 'Amakuru yo kutugeraho',
    newsletter: 'Amakuru mashya',
    newsletterSub: 'Guma uzi amakuru n\'ibikorwa byacu bya buri cyumweru.',
    emailPlaceholder: 'Email yawe',
    subscribe: 'Iyandikishe',
    allRightsReserved: 'Uburenganzira bwose burasubitswe.',
    privacyPolicy: 'Politiki y\'ibanga',
    termsOfService: 'Amategeko n\'amabwiriza',
    registrationPlaceholderName: 'urugero: John Doe',
    registrationPlaceholderFamily: 'urugero: Umuryango wa Smith',
    registrationPlaceholderMember: 'Umuryango',
    registrationPlaceholderPrevious: 'urugero: Angelus Temple',
    quizTitle: 'Ubumenyi bw\'Itorero',
    quizSub: 'Gerageza ubumenyi bwawe ku mateka ya Foursquare',
    quizQuestion: 'Ikibazo',
    quizOf: 'kuri',
    quizExcellent: 'Ubumenyi buhebuje!',
    quizKeepLearning: 'Komeza wige!',
    quizScored: 'Watsinze',
    quizOutOf: 'kuri',
    quizPassedDesc: 'Ufite ubumenyi bukomeye ku mateka y\'itorero ryacu. Wemewe ku mugaragaro nka \'Umushyitsi uzi amateka\'!',
    quizFailedDesc: 'Amateka yacu ni akungahaye kandi arambuye. Turagushishikariza gusura igice cya \'Amateka\' kugira ngo umenye byinshi ku murimo wacu w\'inkingi enye.',
    tryAgain: 'Ongera ugerageze',
    finish: 'Rangiza',
    quizQ1: 'Ninde washinze Itorero rya Foursquare Gospel?',
    quizQ1O1: 'John Wesley',
    quizQ1O2: 'Aimee Semple McPherson',
    quizQ1O3: 'Billy Graham',
    quizQ1O4: 'Martin Luther',
    quizQ2: 'Ni iki \'Foursquare\' isobanura?',
    quizQ2O1: 'Ibihe bine',
    quizQ2O2: 'Amavanjiri ane',
    quizQ2O3: 'Umurimo w\'inkingi enye wa Yesu',
    quizQ2O4: 'Icyerekezo bine',
    quizQ3: 'Ni iyihe muri izi itari imwe mu nkingi enye?',
    quizQ3O1: 'Umukiza',
    quizQ3O2: 'Umubatizashyitsi',
    quizQ3O3: 'Umukiza w\'indwara',
    quizQ3O4: 'Umuhanuzi',
    quizQ4: 'Ni mu wuhe mwaka umuryango wa Foursquare washinzwe?',
    quizQ4O1: '1900',
    quizQ4O2: '1923',
    quizQ4O3: '1950',
    quizQ4O4: '1880',
    wordAccount: 'Konti y\'Ijambo',
    overview: 'Incamake',
    myStudies: 'Inyigisho zanjye',
    studyNotes: 'Inyandiko z\'inyigisho',
    settings: 'Igenamiterere',
    close: 'Funga',
    spiritualGrowth: 'Gukura mu buryo bw\'umwuka',
    myBibleStudies: 'Inyigisho zanjye za Bibiliya',
    personalNotes: 'Inyandiko zanjye',
    trackingJourney: 'Gukurikirana urugendo rwawe mu Jambo.',
    levelDisciple: 'Umwigishwa wo ku rwego rwa 12',
    chaptersRead: 'Ibice byasomwe',
    studiesCompleted: 'Inyigisho zarangiye',
    prayerStreak: 'Iminsi yo gusenga',
    savedVerses: 'Imirongo yabitswe',
    recentProgress: 'Iterambere rya vuba',
    viewAll: 'Reba byose',
    lastAccessed: 'Byasuwe vuba',
    continueJourney: 'Komeza urugendo rwawe',
    continueJourneySub: 'Usigaje ibice 3 gusa ngo urangize inyigisho ya "Itangiriro"!',
    resumeStudy: 'Komeza inyigisho',
    enrollNewStudy: 'Iyandikishe mu nyigisho nshya',
    readFullNote: 'Soma inyandiko yose',
    days: 'Iminsi',
    hours: 'Amasaha',
    ago: 'hashize',
    day: 'umunsi',
    today: 'Uyu munsi',
    yesterday: 'Ejo hashize',
    completed: 'Byarangiye',
    inProgress: 'Biracyakomeza',
    studySubText: 'Inyigisho irambuye y\'ibyanditswe.',
    studyGenesis: 'Itangiriro: Itangira',
    studyRomans: 'Abanyaroma: Ishingiro ry\'ukwizera',
    studyParables: 'Imigani ya Yesu',
    note1Title: 'Ibitekerezo ku buntu',
    note1Preview: 'Ubuntu si ubutoni gusa, ni imbaraga z\'Imana zo guhindura...',
    note2Title: 'Inyandiko z\'inyigisho: Umucyo',
    note2Preview: 'Kugendera mu mucyo bivuze kubaho mu mucyo no mu kuri...',
    note3Title: 'Ibibazo ku Mushumba',
    note3Preview: '1. Ni gute dusobanura imiterere y\'umuco mu 1 Abakorinto?',
  },
  FR: {
    home: 'Accueil',
    live: 'En Direct',
    services: 'Services',
    bibleStudy: 'Étude Bibl.',
    gallery: 'Galerie',
    branches: 'Succursales',
    aboutUs: 'Infos',
    register: 'S\'inscrire',
    give: 'Donner',
    media: 'Médias',
    videoSermons: 'Sermons Vidéo',
    photoGallery: 'Galerie Photos',
    registrationTitle: 'Inscription à l\'Église',
    registrationSub: 'Rejoignez notre famille d\'église aujourd\'hui',
    individual: 'Individuel',
    family: 'Famille',
    fullName: 'Nom Complet',
    familyName: 'Nom de Famille',
    addMember: 'Ajouter un membre',
    familyMembers: 'Membres de la famille',
    visitedBefore: 'Avez-vous déjà visité Grace Community ?',
    yesVisited: 'Oui, je l\'ai fait',
    noVisited: 'Non, première fois',
    completeRegistration: 'Terminer l\'inscription',
    dailyDevotional: 'Dévotion Quotidienne',
    startDayGrace: 'Commencez votre journée avec grâce',
    devotionalSub: 'Cliquez ci-dessous pour générer une dévotion unique, propulsée par l\'IA, pour inspirer votre marche avec Dieu aujourd\'hui.',
    generateDevotional: 'Générer la dévotion d\'aujourd\'hui',
    preparingInspiration: 'Préparation de votre inspiration...',
    reflection: 'Réflexion',
    prayer: 'Prière',
    generateAnother: 'Générer une autre',
    bibleStudyGroups: 'Groupes d\'Étude Biblique',
    bibleStudySub: 'Approfondissez votre compréhension des Écritures et nouez des amitiés durables dans nos petits groupes d\'étude biblique.',
    viewAllGroups: 'Voir tous les groupes',
    scriptureLibrary: 'Bibliothèque d\'Écritures',
    scriptureLibrarySub: 'Accédez à notre collection de versets bibliques pour chaque situation. Téléchargez et partagez ces paroles de vie.',
    exploreScriptures: 'Explorer les Écritures',
    branchDetails: 'Détails de la branche',
    pastor: 'Pasteur',
    serviceTimes: 'Heures de service',
    aboutBranch: 'À propos de cette branche',
    mission: 'Notre Mission',
    history: 'Notre Histoire',
    worshippers: 'Fidèles',
    contactUs: 'Contactez-nous',
    scriptureLibraryTitle: 'Bibliothèque d\'Écritures',
    scriptureLibrarySubText: 'Explorez les paroles de la Bible classées pour votre parcours de vie. Téléchargez un magnifique flyer de votre verset préféré.',
    printFlyer: 'Imprimer le Flyer',
    peaceComfort: 'Paix et Confort',
    strengthCourage: 'Force et Courage',
    hopeFuture: 'Espoir et Futur',
    ourServices: 'Nos Services',
    servicesSub: 'Nous offrons diverses façons de se connecter avec Dieu et notre communauté tout au long de la semaine.',
    sundayWorship: 'Culte du dimanche matin',
    midWeekPrayer: 'Prière en milieu de semaine',
    youthGathering: 'Rassemblement des jeunes',
    communityOutreach: 'Action communautaire',
    welcome: 'Bienvenue à Grace Community',
    heroTitle: 'Vivez la Grâce, Trouvez la Communauté',
    heroSub: 'Un lieu où la foi rencontre la fraternité. Rejoignez-nous pour grandir ensemble en Christ.',
    joinLive: 'Rejoindre le Direct',
    viewServices: 'Voir les Services',
    liveNow: 'En Direct',
    onlineService: 'Rejoignez notre service en ligne',
    watching: 'Spectateurs',
    upcomingStreams: 'Prochains Directs',
    ourBranches: 'Nos Succursales',
    findBranch: 'Trouvez une succursale de Grace Community près de chez vous.',
    churchGallery: 'Galerie de l\'Église',
    capturingMoments: 'Capturer des moments de foi, de fraternité et de service.',
    heritage: 'Notre Héritage',
    foursquareTitle: 'Église de l\'Évangile Foursquare',
    getInvolved: 'Façons de s\'impliquer',
    wantToBeChristian: 'Voulez-vous devenir membre de la foi chrétienne ?',
    previousChurch: 'De quelle église venez-vous ?',
    yesMember: 'Oui, je veux m\'inscrire',
    noMember: 'Pas encore',
    voiceTranslation: 'Traduction Vocale',
    enableTranslation: 'Activer la Traduction en Direct',
    translating: 'Traduction en cours...',
    translationNotice: 'Traduction en temps réel propulsée par l\'IA pour notre famille mondiale.',
    watchOnYoutube: 'Regarder sur YouTube',
    mediaExplorer: 'Explorateur de Médias',
    recentSermons: 'Sermons Récents',
    photoHighlights: 'Photos Marquantes',
    watchNow: 'Regarder Maintenant',
    viewGallery: 'Voir la Galerie',
    unmute: 'Activer le son',
    mute: 'Muet',
    theLivingWord: 'La Parole Vivante',
    livingWordSub: '"Au commencement était la Parole, et la Parole était avec Dieu, et la Parole était Dieu."',
    ourPhilosophy: 'Notre Philosophie',
    illuminatingTruth: 'Illuminer la Vérité',
    biblicalExcellence: 'Excellence Biblique',
    biblicalExcellenceSub: 'Nous croyons en l\'étude méticuleuse des Écritures, en cherchant l\'intention originale et l\'application éternelle du message de Dieu.',
    communityScholars: 'Communauté de Chercheurs',
    communityScholarsSub: 'Word Light n\'est pas seulement une église ; c\'est une communauté de croyants qui sont aussi des étudiants de la Parole, grandissant ensemble en sagesse et en grâce.',
    aiScriptureInsight: 'Aperçu Biblique par l\'IA',
    aiScriptureInsightSub: 'Demandez à l\'IA une perspective théologique profonde sur l\'étude d\'aujourd\'hui...',
    foursquareDesc: 'Grace Community est un fier membre de l\'Église Internationale de l\'Évangile Foursquare. Le terme "Foursquare" représente le ministère quadruple de Jésus-Christ en tant que Sauveur, Baptiseur du Saint-Esprit, Guérisseur et Roi qui Vient.',
    foundationHistory: 'Notre Fondation et notre Histoire',
    foundationHistorySub: 'Fondé en 1923 par Aimee Semple McPherson, le mouvement Foursquare a commencé avec l\'ouverture de l\'Angelus Temple à Los Angeles. Sœur Aimee a été pionnière dans l\'utilisation de la technologie moderne et des arts créatifs pour partager l\'Évangile, un héritage que nous poursuivons aujourd\'hui.',
    founder: 'Fondatrice',
    established: 'Établie',
    savior: 'Sauveur',
    saviorDesc: 'Jésus est notre Sauveur',
    baptizer: 'Baptiseur',
    baptizerDesc: 'Du Saint-Esprit',
    healer: 'Guérisseur',
    healerDesc: 'Jésus est notre Guérisseur',
    comingKing: 'Roi qui Vient',
    comingKingDesc: 'Il reviendra bientôt',
    globalFamily: 'Nous sommes une famille mondiale de plus de 8 millions de membres dans plus de 140 pays, unis par notre passion pour la Grande Commission et notre engagement envers la coopération interconfessionnelle.',
    ourMission: 'Notre Mission',
    ourMissionSub: 'Présenter l\'Évangile Foursquare à chaque personne dans chaque pays, en faisant des disciples qui font des disciples.',
    deepStudy: 'Étude Approfondie',
    listen: 'Écouter',
    scrollToExplore: 'Faire défiler pour explorer',
    nextService: 'Prochain Service',
    sundayMorning: 'Dimanche Matin',
    mainSanctuary: 'Sanctuaire Principal',
    studySessions: 'Sessions d\'Étude',
    studySessionsSub: 'Rejoignez notre voyage académique et spirituel rigoureux à travers la Parole vivante de Dieu.',
    deepExegesis: 'Exégèse Profonde',
    deepExegesisSub: 'Une étude analytique verset par verset des Écritures, centrée sur les langues originales et le contexte historique.',
    theologicalSeminar: 'Séminaire Théologique',
    theologicalSeminarSub: 'Discussions avancées sur la théologie systématique, l\'histoire de l\'église et l\'apologétique pour le croyant moderne.',
    hermeneuticsWorkshop: 'Atelier d\'Herméneutique',
    hermeneuticsWorkshopSub: 'Formation pratique dans l\'art et la science de l\'interprétation biblique et de la préparation des sermons.',
    propheticInsight: 'Aperçu Prophétique',
    propheticInsightSub: 'Explorer les livres prophétiques de la Bible et leur pertinence par rapport aux événements mondiaux actuels.',
    studyQuote: '"Efforce-toi de te présenter devant Dieu comme un homme éprouvé, un ouvrier qui n\'a point à rougir."',
    worshipQuote: '"Car là où deux ou trois sont assemblés en mon nom, je suis au milieu d\'eux."',
    studySessionsDesc: 'Nos sessions d\'étude sont conçues pour stimuler votre intellect et nourrir votre esprit. Chaque session est une étape plus profonde dans la sagesse infinie des Écritures.',
    worshipSessionsDesc: 'Chaque service est une occasion unique de rencontrer la présence de Dieu et de grandir en communauté. Que vous nous rejoigniez pour la première fois ou pour la centième, vous avez votre place ici.',
    enrollInSession: 'S\'inscrire à la Session',
    planYourVisit: 'Planifiez votre Visite',
    viewCurriculum: 'Voir le Programme',
    watchPastServices: 'Voir les Services Passés',
    ourSchools: 'Nos Écoles',
    ourSchoolsSub: 'L\'Église CityLight est fière de gérer des écoles maternelles et primaires dans quatre régions différentes du Rwanda. Nous croyons en une éducation de qualité ancrée dans les valeurs chrétiennes pour construire un avenir meilleur pour nos enfants.',
    ourMinistry: 'Notre Ministère',
    ourMinistrySub: 'Notre ministère s\'étend au-delà des murs de l\'église. Nous nous engageons dans la formation au leadership, le développement social et les projets économiques qui soutiennent les communautés nationales et locales.',
    leadership: 'Leadership',
    leadershipSub: 'Formation continue pour le renforcement des capacités.',
    development: 'Développement',
    developmentSub: 'Activités sociales et projets économiques.',
    wordStudy: 'Étude de la Parole',
    wordArchive: 'Archives de la Parole',
    philosophy: 'Philosophie',
    ourHistory: 'Notre Histoire',
    ourValues: 'Nos Valeurs',
    generalInfo: 'Infos Générales',
    mainServices: 'Services Principaux',
    sermons: 'Sermons',
    resources: 'Ressources',
    ourSchool: 'Notre École',
    ourMinistryNav: 'Notre Ministère',
    selectLanguage: 'Choisir la Langue',
    aiPoweredTranslation: 'Traduction par l\'IA',
    unmuteVoice: 'Activer la Voix',
    muteVoice: 'Couper la Voix',
    switchToLightMode: 'Passer au Mode Clair',
    switchToDarkMode: 'Passer au Mode Sombre',
    churchKnowledgeQuiz: 'Quiz sur l\'Église',
    christianMember: 'Membre Chrétien',
    visitor: 'Visiteur',
    heritageScore: 'Score d\'Héritage',
    from: 'De',
    fromChurch: 'De l\'Église',
    yes: 'Oui',
    no: 'Non',
    unmuteNav: 'Activer',
    muteNav: 'Muet',
    footerDesc: 'Une communauté de foi dédiée à aimer Dieu et à aimer nos prochains. Rejoignez-nous dans notre voyage de foi.',
    quickLinks: 'Liens Rapides',
    contactInfo: 'Infos de Contact',
    newsletter: 'Newsletter',
    newsletterSub: 'Restez informé de nos actualités et événements hebdomadaires.',
    emailPlaceholder: 'Votre adresse e-mail',
    subscribe: 'S\'abonner',
    allRightsReserved: 'Tous droits réservés.',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    registrationPlaceholderName: 'ex: Jean Dupont',
    registrationPlaceholderFamily: 'ex: La Famille Martin',
    registrationPlaceholderMember: 'Membre',
    registrationPlaceholderPrevious: 'ex: Angelus Temple',
    quizTitle: 'Connaissance de l\'Église',
    quizSub: 'Testez votre héritage Foursquare',
    quizQuestion: 'Question',
    quizOf: 'sur',
    quizExcellent: 'Excellente Connaissance !',
    quizKeepLearning: 'Continuez à Apprendre !',
    quizScored: 'Vous avez obtenu',
    quizOutOf: 'sur',
    quizPassedDesc: 'Vous avez une solide compréhension de l\'héritage de notre église. Vous êtes officiellement reconnu comme un \'Visiteur Averti\' !',
    quizFailedDesc: 'Notre héritage est riche et profond. Nous vous encourageons à explorer la section \'À propos\' pour en savoir plus sur notre ministère quadruple.',
    tryAgain: 'Réessayer',
    finish: 'Terminer',
    quizQ1: 'Qui a fondé l\'Église de l\'Évangile Foursquare ?',
    quizQ1O1: 'John Wesley',
    quizQ1O2: 'Aimee Semple McPherson',
    quizQ1O3: 'Billy Graham',
    quizQ1O4: 'Martin Luther',
    quizQ2: 'Que représente le \'Foursquare\' ?',
    quizQ2O1: 'Quatre Saisons',
    quizQ2O2: 'Quatre Évangiles',
    quizQ2O3: 'Ministère quadruple de Jésus',
    quizQ2O4: 'Quatre Directions',
    quizQ3: 'Lequel de ceux-ci n\'est PAS l\'un des quatre piliers ?',
    quizQ3O1: 'Sauveur',
    quizQ3O2: 'Baptiseur',
    quizQ3O3: 'Guérisseur',
    quizQ3O4: 'Prophète',
    quizQ4: 'En quelle année le mouvement Foursquare a-t-il été fondé ?',
    quizQ4O1: '1900',
    quizQ4O2: '1923',
    quizQ4O3: '1950',
    quizQ4O4: '1880',
    wordAccount: 'Compte de la Parole',
    overview: 'Aperçu',
    myStudies: 'Mes Études',
    studyNotes: 'Notes d\'Étude',
    settings: 'Paramètres',
    close: 'Fermer',
    spiritualGrowth: 'Croissance Spirituelle',
    myBibleStudies: 'Mes Études Bibliques',
    personalNotes: 'Notes Personnelles',
    trackingJourney: 'Suivi de votre voyage à travers la Parole.',
    levelDisciple: 'Disciple de Niveau 12',
    chaptersRead: 'Chapitres Lus',
    studiesCompleted: 'Études Terminées',
    prayerStreak: 'Série de Prières',
    savedVerses: 'Versets Enregistrés',
    recentProgress: 'Progrès Récents',
    viewAll: 'Voir Tout',
    lastAccessed: 'Dernier accès',
    continueJourney: 'Continuez Votre Voyage',
    continueJourneySub: 'Vous n\'êtes qu\'à 3 chapitres de terminer le guide d\'étude de la "Genèse" !',
    resumeStudy: 'Reprendre l\'Étude',
    enrollNewStudy: 'S\'inscrire à une Nouvelle Étude',
    readFullNote: 'Lire la Note Complète',
    days: 'Jours',
    hours: 'Heures',
    ago: 'il y a',
    day: 'jour',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    completed: 'Terminé',
    inProgress: 'En Cours',
    studySubText: 'Étude approfondie des écritures.',
    studyGenesis: 'Genèse : Le Commencement',
    studyRomans: 'Romains : Fondements de la Foi',
    studyParables: 'Les Paraboles de Jésus',
    note1Title: 'Réflexions sur la Grâce',
    note1Preview: 'La grâce n\'est pas seulement une faveur imméritée, c\'est la puissance de Dieu pour transformer...',
    note2Title: 'Notes de Sermon : La Lumière',
    note2Preview: 'Marcher dans la lumière signifie vivre dans la transparence et la vérité...',
    note3Title: 'Questions pour le Pasteur',
    note3Preview: '1. Comment interprétons-le contexte culturel de 1 Corinthiens ?',
  },
  KIS: {
    home: 'Nyumbani',
    live: 'Mubashara',
    services: 'Ibada',
    bibleStudy: 'Biblia',
    gallery: 'Picha',
    branches: 'Matawi',
    aboutUs: 'Sisi',
    register: 'Jisajili',
    give: 'Toa',
    media: 'Vyombo vya Habari',
    videoSermons: 'Mahubiri ya Video',
    photoGallery: 'Matunzio ya Picha',
    registrationTitle: 'Usajili wa Kanisa',
    registrationSub: 'Jiunge na familia yetu ya kanisa leo',
    individual: 'Binafsi',
    family: 'Familia',
    fullName: 'Jina Kamili',
    familyName: 'Jina la Familia',
    addMember: 'Ongeza Mwanachama',
    familyMembers: 'Wanafamilia',
    visitedBefore: 'Je, umewahi kutembelea Grace Community hapo awali?',
    yesVisited: 'Ndiyo, nimefika',
    noVisited: 'Hapana, mara ya kwanza',
    completeRegistration: 'Kamilisha Usajili',
    dailyDevotional: 'Ibada ya Kila Siku',
    startDayGrace: 'Anza Siku Yako kwa Neema',
    devotionalSub: 'Bonyeza hapa chini ili upate ibada ya kipekee, inayotumiwa na AI, ili kuhamasisha matembezi yako na Mungu leo.',
    generateDevotional: 'Tengeneza Ibada ya Leo',
    preparingInspiration: 'Tunatayarisha msukumo wako...',
    reflection: 'Tafakari',
    prayer: 'Maombi',
    generateAnother: 'Tengeneza Nyingine',
    bibleStudyGroups: 'Vikundi vya Mafunzo ya Biblia',
    bibleStudySub: 'Ongeza uelewa wako wa Maandiko na ujenge urafiki wa kudumu katika mafunzo yetu ya Biblia ya vikundi vidogo.',
    viewAllGroups: 'Angalia Vikundi Vyote',
    scriptureLibrary: 'Maktaba ya Maandiko',
    scriptureLibrarySub: 'Pata mkusanyiko wetu wa aya za Biblia kwa kila hali. Pakua na ushiriki maneno haya ya uzima.',
    exploreScriptures: 'Chunguza Maandiko',
    branchDetails: 'Maelezo ya Tawi',
    pastor: 'Mchungaji',
    serviceTimes: 'Muda wa Ibada',
    aboutBranch: 'Kuhusu Tawi hili',
    mission: 'Dhamira Yetu',
    history: 'Historia Yetu',
    worshippers: 'Waumini',
    contactUs: 'Wasiliana Nasi',
    scriptureLibraryTitle: 'Maktaba ya Maandiko',
    scriptureLibrarySubText: 'Chunguza maneno ya Biblia yaliyopangwa kwa ajili ya safari yako ya maisha. Pakua picha nzuri ya aya unayoipenda.',
    printFlyer: 'Chapa Picha',
    peaceComfort: 'Amani na Faraja',
    strengthCourage: 'Nguvu na Ujasiri',
    hopeFuture: 'Tumaini na Wakati Ujao',
    ourServices: 'Huduma Zetu',
    servicesSub: 'Tunatoa njia mbalimbali za kuungana na Mungu na jamii yetu wiki nzima. Jiunge nasi katika mikutano yetu yoyote iliyopangwa.',
    sundayWorship: 'Ibada ya Jumapili Asubuhi',
    midWeekPrayer: 'Maombi ya Katikati ya Wiki',
    youthGathering: 'Mkutano wa Vijana',
    communityOutreach: 'Ufikiaji wa Jamii',
    welcome: 'Karibu Grace Community',
    heroTitle: 'Pata Neema, Pata Jumuiya',
    heroSub: 'Mahali ambapo imani hukutana na ushirika. Jiunge nasi tunapokua pamoja katika Kristo.',
    joinLive: 'Jiunge Mubashara',
    viewServices: 'Angalia Ibada',
    liveNow: 'Sasa Hivi',
    onlineService: 'Jiunge na Ibada yetu ya Mtandaoni',
    watching: 'Watazamaji',
    upcomingStreams: 'Matangazo Yajayo',
    ourBranches: 'Matawi Yetu',
    findBranch: 'Tafuta tawi la Grace Community karibu nawe.',
    churchGallery: 'Picha za Kanisa',
    capturingMoments: 'Kurekodi nyakati za imani, ushirika, na huduma.',
    heritage: 'Urithi Wetu',
    foursquareTitle: 'Kanisa la Foursquare Gospel',
    getInvolved: 'Njia za Kushiriki',
    wantToBeChristian: 'Je, unataka kuwa muumini wa imani ya Kikristo?',
    previousChurch: 'Unatoka kanisa gani?',
    yesMember: 'Ndiyo, nataka kujiunga',
    noMember: 'Bado',
    voiceTranslation: 'Tafsiri ya Sauti',
    enableTranslation: 'Washa Tafsiri ya Moja kwa Moja',
    translating: 'Inatafsiri...',
    translationNotice: 'Tafsiri ya wakati halisi inayotumiwa na AI kwa familia yetu ya kimataifa.',
    watchOnYoutube: 'Tazama kwenye YouTube',
    mediaExplorer: 'Kivinjari cha Vyombo vya Habari',
    recentSermons: 'Mahubiri ya Hivi Karibuni',
    photoHighlights: 'Picha Muhimu',
    watchNow: 'Tazama Sasa',
    viewGallery: 'Tazama Matunzio',
    unmute: 'Washa sauti',
    mute: 'Nyamazisha',
    theLivingWord: 'Neno Hai',
    livingWordSub: '"Hapo mwanzo kulikuwako Neno, naye Neno alikuwako kwa Mungu, naye Neno alikuwa Mungu."',
    ourPhilosophy: 'Falsafa Yetu',
    illuminatingTruth: 'Kuangazia Ukweli',
    biblicalExcellence: 'Ubora wa Kibiblia',
    biblicalExcellenceSub: 'Tunaamini katika uchunguzi makini wa maandiko, tukitafuta nia ya asili na matumizi ya milele ya ujumbe wa Mungu.',
    communityScholars: 'Jumuiya ya Wasomi',
    communityScholarsSub: 'Word Light si kanisa tu; ni jumuiya ya waumini ambao pia ni wanafunzi wa Neno, wakikua pamoja katika hekima na neema.',
    aiScriptureInsight: 'Ufahamu wa Maandiko wa AI',
    aiScriptureInsightSub: 'Uliza AI kwa mtazamo wa kina wa kitheolojia kuhusu somo la leo...',
    foursquareDesc: 'Grace Community ni mwanachama anayejivunia wa Kanisa la Kimataifa la Foursquare Gospel. Neno "Foursquare" linawakilisha huduma ya mara nne ya Yesu Kristo kama Mwokozi, Mbatizaji wa Roho Mtakatifu, Mponyaji, na Mfalme Anayekuja.',
    foundationHistory: 'Msingi na Historia Yetu',
    foundationHistorySub: 'Ilianzishwa mwaka wa 1923 na Aimee Semple McPherson, harakati ya Foursquare ilianza na ufunguzi wa Angelus Temple huko Los Angeles. Dada Aimee alikuwa painia katika matumizi ya teknolojia ya kisasa na sanaa ya ubunifu kushiriki Injili, urithi ambao tunaendeleza leo.',
    founder: 'Mwanzilishi',
    established: 'Ilianzishwa',
    savior: 'Mwokozi',
    saviorDesc: 'Yesu ni Mwokozi wetu',
    baptizer: 'Mbatizaji',
    baptizerDesc: 'Wa Roho Mtakatifu',
    healer: 'Mponyaji',
    healerDesc: 'Yesu ni Mponyaji wetu',
    comingKing: 'Mfalme Anayekuja',
    comingKingDesc: 'Atakuja tena',
    globalFamily: 'Sisi ni familia ya kimataifa ya wanachama zaidi ya milioni 8 katika nchi zaidi ya 140, tukiwa tumeunganishwa na shauku yetu kwa Agizo Kuu na kujitolea kwetu kwa ushirikiano wa madhehebu mbalimbali.',
    ourMission: 'Dhamira Yetu',
    ourMissionSub: 'Kuwasilisha Injili ya Foursquare kwa kila mtu katika kila nchi, tukifanya wanafunzi wanaofanya wanafunzi.',
    deepStudy: 'Mafunzo ya Kina',
    listen: 'Sikiliza',
    scrollToExplore: 'Sogeza ili Kuchunguza',
    nextService: 'Ibada Inayofuata',
    sundayMorning: 'Jumapili Asubuhi',
    mainSanctuary: 'Patakatifu Pakuu',
    studySessions: 'Vipindi vya Mafunzo',
    studySessionsSub: 'Jiunge na safari yetu kali ya kitaaluma na kiroho kupitia Neno hai la Mungu.',
    deepExegesis: 'Ufafanuzi wa Kina',
    deepExegesisSub: 'Uchunguzi wa uchambuzi wa aya kwa aya wa maandiko, ukizingatia lugha asilia na muktadha wa kihistoria.',
    theologicalSeminar: 'Semina ya Kitheolojia',
    theologicalSeminarSub: 'Majadiliano ya kina kuhusu theolojia ya kimfumo, historia ya kanisa, na utetezi wa imani kwa muumini wa kisasa.',
    hermeneuticsWorkshop: 'Warsha ya Hermeneutics',
    hermeneuticsWorkshopSub: 'Mafunzo ya vitendo katika sanaa na sayansi ya tafsiri ya Biblia na maandalizi ya mahubiri.',
    propheticInsight: 'Ufahamu wa Unabii',
    propheticInsightSub: 'Kuchunguza vitabu vya unabii vya Biblia na umuhimu wake kwa matukio ya sasa ya ulimwengu.',
    studyQuote: '"Jitahidi kujionyesha kuwa umekubaliwa na Mungu, mtenda kazi asiye na sababu ya kutahayari."',
    worshipQuote: '"Kwa kuwa walipo wawili watatu wamekusanyika kwa jina langu, nami nipo papo hapo katikati yao."',
    studySessionsDesc: 'Vipindi vyetu vya mafunzo vimeundwa ili kutoa changamoto kwa akili yako na kulisha roho yako. Kila kipindi ni hatua ya ndani zaidi katika hekima isiyo na mwisho ya maandiko.',
    worshipSessionsDesc: 'Kila ibada ni fursa ya kipekee ya kukutana na uwepo wa Mungu na kukua katika jumuiya. Iwe unajiunga nasi kwa mara ya kwanza au ya mia moja, kuna nafasi kwa ajili yako hapa.',
    enrollInSession: 'Jiandikishe kwa Kipindi',
    planYourVisit: 'Panga Ziara Yako',
    viewCurriculum: 'Angalia Mtaala',
    watchPastServices: 'Tazama Ibada Zilizopita',
    ourSchools: 'Shule Zetu',
    ourSchoolsSub: 'Kanisa la CityLight linajivunia kuendesha shule za chekechea na msingi katika maeneo manne tofauti ya Rwanda. Tunaamini katika kutoa elimu bora iliyojikita katika maadili ya Kikristo ili kujenga maisha bora ya baadaye kwa watoto wetu.',
    ourMinistry: 'Huduma Yetu',
    ourMinistrySub: 'Huduma yetu inaenea zaidi ya kuta za kanisa. Tumejitolea kwa mafunzo ya uongozi, maendeleo ya kijamii, na miradi ya kiuchumi inayosaidia jamii za kitaifa na za mitaa.',
    leadership: 'Uongozi',
    leadershipSub: 'Mafunzo ya mara kwa mara kwa ajili ya kujenga uwezo.',
    development: 'Maendeleo',
    developmentSub: 'Shughuli za kijamii na miradi ya kiuchumi.',
    wordStudy: 'Mafunzo ya Neno',
    wordArchive: 'Maktaba ya Neno',
    philosophy: 'Falsafa',
    ourHistory: 'Historia Yetu',
    ourValues: 'Maadili Yetu',
    generalInfo: 'Habari za Jumla',
    mainServices: 'Ibada Kuu',
    sermons: 'Mahubiri',
    resources: 'Rasilimali',
    ourSchool: 'Shule Yetu',
    ourMinistryNav: 'Huduma Yetu',
    selectLanguage: 'Chagua Lugha',
    aiPoweredTranslation: 'Tafsiri ya AI',
    unmuteVoice: 'Washa Sauti',
    muteVoice: 'Nyamazisha Sauti',
    switchToLightMode: 'Badili hadi Hali ya Mwanga',
    switchToDarkMode: 'Badili hadi Hali ya Giza',
    churchKnowledgeQuiz: 'Maswali ya Maarifa ya Kanisa',
    christianMember: 'Mwanachama wa Kikristo',
    visitor: 'Mgeni',
    heritageScore: 'Alama za Urithi',
    from: 'Kutoka',
    fromChurch: 'Kutoka Kanisani',
    yes: 'Ndiyo',
    no: 'Hapana',
    unmuteNav: 'Washa sauti',
    muteNav: 'Nyamazisha',
    footerDesc: 'Jumuiya ya imani iliyojitolea kumpenda Mungu na kuwapenda majirani zetu. Jiunge nasi tunaposafiri pamoja katika imani.',
    quickLinks: 'Viungo vya Haraka',
    contactInfo: 'Habari za Mawasiliano',
    newsletter: 'Jarida',
    newsletterSub: 'Pata habari kuhusu habari na matukio yetu ya kila wiki.',
    emailPlaceholder: 'Barua pepe yako',
    subscribe: 'Jiandikishe',
    allRightsReserved: 'Haki zote zimehifadhiwa.',
    privacyPolicy: 'Sera ya Faragha',
    termsOfService: 'Masharti ya Huduma',
    registrationPlaceholderName: 'k.m. John Doe',
    registrationPlaceholderFamily: 'k.m. Familia ya Smith',
    registrationPlaceholderMember: 'Mwanachama',
    registrationPlaceholderPrevious: 'k.m. Angelus Temple',
    quizTitle: 'Maarifa ya Kanisa',
    quizSub: 'Jaribu urithi wako wa Foursquare',
    quizQuestion: 'Swali',
    quizOf: 'kati ya',
    quizExcellent: 'Maarifa Bora!',
    quizKeepLearning: 'Endelea Kujifunza!',
    quizScored: 'Ulipata',
    quizOutOf: 'kati ya',
    quizPassedDesc: 'Una uelewa mzuri wa urithi wa kanisa letu. Unatambuliwa rasmi kama \'Mgeni Mwenye Maarifa\'!',
    quizFailedDesc: 'Urithi wetu ni tajiri na wa kina. Tunakuhimiza uchunguze sehemu ya \'Kuhusu\' ili ujifunze zaidi kuhusu huduma yetu ya mara nne.',
    tryAgain: 'Jaribu Tena',
    finish: 'Maliza',
    quizQ1: 'Nani alianzisha Kanisa la Foursquare Gospel?',
    quizQ1O1: 'John Wesley',
    quizQ1O2: 'Aimee Semple McPherson',
    quizQ1O3: 'Billy Graham',
    quizQ1O4: 'Martin Luther',
    quizQ2: 'Je, \'Foursquare\' inawakilisha nini?',
    quizQ2O1: 'Misimu Minne',
    quizQ2O2: 'Injili Nne',
    quizQ2O3: 'Huduma ya mara nne ya Yesu',
    quizQ2O4: 'Mielekeo Minne',
    quizQ3: 'Ni ipi kati ya hizi SI miongoni mwa nguzo nne?',
    quizQ3O1: 'Mwokozi',
    quizQ3O2: 'Mbatizaji',
    quizQ3O3: 'Mponyaji',
    quizQ3O4: 'Nabii',
    quizQ4: 'Mvuguvugu la Foursquare lilianzishwa mwaka gani?',
    quizQ4O1: '1900',
    quizQ4O2: '1923',
    quizQ4O3: '1950',
    quizQ4O4: '1880',
    wordAccount: 'Akaunti ya Neno',
    overview: 'Muhtasari',
    myStudies: 'Mafunzo Yangu',
    studyNotes: 'Maelezo ya Mafunzo',
    settings: 'Mipangilio',
    close: 'Funga',
    spiritualGrowth: 'Ukuaji wa Kiroho',
    myBibleStudies: 'Mafunzo Yangu ya Biblia',
    personalNotes: 'Maelezo ya Kibinafsi',
    trackingJourney: 'Kufuatilia safari yako kupitia Neno.',
    levelDisciple: 'Mwanafunzi wa Ngazi ya 12',
    chaptersRead: 'Sura Zilizosomwa',
    studiesCompleted: 'Mafunzo Yaliyokamilika',
    prayerStreak: 'Mfululizo wa Maombi',
    savedVerses: 'Aya Zilizohifadhiwa',
    recentProgress: 'Maendeleo ya Hivi Karibuni',
    viewAll: 'Tazama Zote',
    lastAccessed: 'Ilifikiwa mara ya mwisho',
    continueJourney: 'Endelea na Safari Yako',
    continueJourneySub: 'Umebakiza sura 3 tu kukamilisha mwongozo wa mafunzo wa "Mwanzo"!',
    resumeStudy: 'Endelea na Mafunzo',
    enrollNewStudy: 'Jiandikishe kwa Mafunzo Mapya',
    readFullNote: 'Soma Maelezo Kamili',
    days: 'Siku',
    hours: 'Masaa',
    ago: 'zilizopita',
    day: 'siku',
    today: 'Leo',
    yesterday: 'Jana',
    completed: 'Imekamilika',
    inProgress: 'Inaendelea',
    studySubText: 'Mafunzo ya kina ya maandiko.',
    studyGenesis: 'Mwanzo: Mwanzo',
    studyRomans: 'Warumi: Misingi ya Imani',
    studyParables: 'Mifano ya Yesu',
    note1Title: 'Tafakari kuhusu Neema',
    note1Preview: 'Neema si upendeleo tu usiofaa, ni nguvu ya Mungu ya kubadilisha...',
    note2Title: 'Maelezo ya Mahubiri: Mwanga',
    note2Preview: 'Kutembea katika mwanga inamaanisha kuishi katika uwazi na ukweli...',
    note3Title: 'Maswali kwa Mchungaji',
    note3Preview: '1. Tunatafsiri vipi muktadha wa kitamaduni wa 1 Wakorintho?',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
